//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillItem = new HashSet<BillItem>();
        }
    
        public int BillId { get; set; }
        public System.DateTime Date { get; set; }
        public int PersonId { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public bool isCustomer { get; set; }
        public bool isDone { get; set; }
    
        public virtual City City { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillItem> BillItem { get; set; }
    }
}
