//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Bill
    {
        public string Person { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TotalPrice { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public bool isCustomer { get; set; }
        public bool isDone { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> CityId { get; set; }
        public int BillId { get; set; }
    }
}
